services:
  backend:
    build: backend
    image: lehuannhatrang/lipo-solar-backend:latest
    ports:
      - "8000:5000"
    command: flask
    env_file:
      - backend/prod.env
    depends_on:
      - db
    restart: always
  celery-worker:
    build: backend
    command: worker
    env_file:
      - backend/prod.env
    depends_on:
      - redis
    restart: always
  frontend:
    build: frontend
    image: lehuannhatrang/lipo-solar-frontend:latest
    ports:
      - "8001:8501"
    env_file:
      - frontend/prod.env
    restart: always
  db:
    image: postgres
    ports:
     - "32432:5432"
    volumes:
       - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./backend/db_data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  