services:
  backend:
    build: .
    image: lehuannhatrang/lipo-solar-backend:latest
    ports:
      - "8000:5000"
    command: /usr/src/app/bootstrap.sh flask
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
     - "32432:5432"
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./db_data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"