apiVersion: v1
kind: PersistentVolume
metadata:
  name: trendz-app-pv
  labels:
    app: trendz-app-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"  # Replace with the actual path on your node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trendz-app-pvc
  namespace: trendz
  labels:
    app: trendz-app-pvc-label
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual 
