apiVersion: v1
kind: ConfigMap
metadata:
  name: trendz-app-db-config
  namespace: trendz
  labels:
    name: trendz-app-db-config-label
data:
  DATABASE_TS_TYPE: sql
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.22.11:32432/trendz
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
---
