[theme]
primaryColor="#00897b"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
[client]
toolbarMode = "minimal"
showSidebarNavigation = false
[ui]
hideTopBar = true